version: '3'
services:
    db:
        image: postgres
        ports:
            - '5432:5432'
        restart: always
        environment:
            POSTGRES_PASSWORD: 20200407
        volumes:
            - ./docker/pgdata:/var/lib/postgresql/data
